version: '3.8'
services:
  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    restart: always
    ports:
      - 3100:3100
    volumes:
      - ./loki-config.yaml:/mnt/config/loki-config.yaml
    command:
      - '--config.file=/mnt/config/loki-config.yaml'
    networks:
      - grafana_monitoring

volumes:
  loki_data: {}

networks:
  grafana_monitoring:
    external: true
