global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'main'
    static_configs:
      - targets: ['k10c204.p.ssafy.io:8000']
