version: '3.8'

services:
  redis:
    container_name: redis
    hostname: redis
    image: 54.180.55.106:5000/redis
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - jenkins_egg-log-net
    volumes:
      - redis-data:/data
    user: root
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

networks:
  jenkins_egg-log-net:
    external: true

volumes:
  redis-data:
