server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://monitor.egg-log.org/loki/loki/api/v1/push

scrape_configs:
  - job_name: main-error
    static_configs:
      - targets:
          - main:8010
        labels:
          job: main-error-logs
          __path__: /var/lib/docker/containers/*/*.log

    pipeline_stages:
      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attrs.tag

      - regex:
          expression: (?P<image_name>(?:[^|]+[^|])).(?P<container_name>(?:[^|]+[^|])).(?P<image_id>(?:[^|]+[^|])).(?P<container_id>(?:[^|]+[^|]))
          source: "tag"
