version: '3.8'

services:
  main:
    container_name: main
    image: kimdahui/main
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - /home/ubuntu/services/main:/var/logs/main:rwo
    environment:
      - TZ=Asia/Seoul
    ports:
      - "8010:8010"
    networks:
      - jenkins_egg-log-net

networks:
  jenkins_egg-log-net:
    external: true
