# 빌드 스테이지
FROM amazoncorretto:17.0.7-alpine AS builder
USER root
WORKDIR /main-service
COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY gradle.properties .
COPY settings.gradle .
COPY src src

# timezone 설정
RUN apk add --update tzdata
ENV TZ=Asia/Seoul

# gradlew 실행 권한 부여
RUN chmod +x ./gradlew
RUN ./gradlew bootJar

# 실행 스테이지
FROM openjdk:17
WORKDIR /main-service
COPY --from=builder /main-service/build/libs/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
